//go:build linux

package main

import (
	"bytes"
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tyler-rich/shell-mcp/internal/gate/gatetest"
)

func runCmd(args []string, stdin string) (code int, stdout, stderr string) {
	var out, errb bytes.Buffer
	code = run(args, strings.NewReader(stdin), &out, &errb)
	return code, out.String(), errb.String()
}

func TestPolkitUsage(t *testing.T) {
	code, out, errb := runCmd([]string{"polkit"}, "")
	if code != 2 || out != "" || !strings.Contains(errb, "usage: shell-mcp-gate polkit --policy <file> --user <name>") {
		t.Fatalf("polkit: %d %q %q", code, out, errb)
	}
}

// A malformed forced command still answers with one JSON response (so the
// server gets install_insecure, not a broken session), and exits 0.
func TestServeMalformedForcedCommand(t *testing.T) {
	for _, args := range [][]string{{"serve"}, {"serve", "--policy"}, {"serve", "--policy", "/x", "--bogus"}, {"serve", "--policy", "/x", "extra"}} {
		code, out, errb := runCmd(args, `{"v":1,"id":"a","op":"hello"}`+"\n")
		var r struct {
			OK    bool `json:"ok"`
			Error struct {
				Code string `json:"code"`
			} `json:"error"`
		}
		if code != 0 || errb != "" || json.Unmarshal([]byte(out), &r) != nil || r.OK || r.Error.Code != "install_insecure" {
			t.Fatalf("%v: %d %q %q", args, code, out, errb)
		}
	}
}

func TestCheckPolicy(t *testing.T) {
	if code, _, errb := runCmd([]string{"check-policy"}, ""); code != 2 || !strings.Contains(errb, "--policy") {
		t.Fatalf("usage: %d %q", code, errb)
	}
	// Under production trust a policy owned by the test uid fails the
	// ownership check; check-policy reports it and exits 1.
	d := gatetest.SecureDir(t)
	p := filepath.Join(d, "policy.yaml")
	gatetest.WriteFile(t, p, "version: 1\nmax_tier: read\n", 0o644)
	code, out, _ := runCmd([]string{"check-policy", "--policy", p}, "")
	if code != 1 || !strings.Contains(out, "FAIL") || !strings.Contains(out, "owned by uid") {
		t.Fatalf("check-policy: %d\n%s", code, out)
	}
	if !strings.Contains(out, "sandbox:") && !strings.Contains(out, "Landlock") {
		t.Fatalf("check-policy must report the sandbox probe:\n%s", out)
	}
}

func TestVersion(t *testing.T) {
	code, out, _ := runCmd([]string{"version"}, "")
	if code != 0 || !strings.HasPrefix(out, "shell-mcp-gate dev") {
		t.Fatalf("version: exit %d, %q", code, out)
	}
}

func TestUnknownCommand(t *testing.T) {
	if code, _, _ := runCmd([]string{"exec"}, ""); code != 2 {
		t.Fatalf("unknown command exit %d", code)
	}
}

// TestCheckPolicyWarnsGTFOBins: with test trust (so the fixture policy
// loads), check-policy prints a WARN line naming the command and its
// escape-technique categories.
func TestCheckPolicyWarnsGTFOBins(t *testing.T) {
	d := gatetest.SecureDir(t)
	gatetest.WriteFile(t, filepath.Join(d, "bin", "tar"), "invented binary\n", 0o755)
	p := filepath.Join(d, "etc", "policy.yaml")
	gatetest.WriteFile(t, p, "version: 1\nmax_tier: read\nsandbox:\n  landlock: best-effort\n  system_read_exec: ["+filepath.Join(d, "bin")+
		"]\ncommands:\n  - id: list-archive\n    path: "+filepath.Join(d, "bin", "tar")+"\n    tier: read\n    templates: [[\"-tf\", \"{path:read}\"]]\n", 0o644)
	var out, errb bytes.Buffer
	checkPolicyWith([]string{"--policy", p}, &out, &errb, gatetest.Trust())
	if !strings.Contains(out.String(), "WARN commands[list-archive]") || !strings.Contains(out.String(), "GTFOBins") ||
		!strings.Contains(out.String(), "command execution") {
		t.Fatalf("check-policy:\n%s", out.String())
	}
}

func TestPolkitCommand(t *testing.T) {
	d := gatetest.SecureDir(t)
	p := filepath.Join(d, "etc", "policy.yaml")
	gatetest.WriteFile(t, p, "version: 1\nmax_tier: operator\nservices:\n  control:\n    units: [example-app.service]\n    verbs: [restart]\n", 0o644)
	run := func(args ...string) (int, string, string) {
		var out, errb bytes.Buffer
		code := polkitWith(args, &out, &errb, gatetest.Trust())
		return code, out.String(), errb.String()
	}
	code, out, errb := run("--policy", p, "--user", "nobody")
	if code != 0 || errb != "" || !strings.Contains(out, `subject.user !== "nobody"`) || !strings.Contains(out, `"example-app.service": ["restart"]`) ||
		!strings.HasPrefix(out, "// Generated by shell-mcp-gate polkit") {
		t.Fatalf("polkit: %d %q\n%s", code, errb, out)
	}
	if code, _, errb := run("--policy", p); code != 2 || !strings.Contains(errb, "--user") {
		t.Fatalf("usage: %d %q", code, errb)
	}
	if code, _, errb := run("--policy", p, "--user", "svc-no-such-user"); code != 1 || !strings.Contains(errb, "svc-no-such-user") {
		t.Fatalf("unknown user: %d %q", code, errb)
	}
	if code, _, errb := run("--policy", p, "--user", "root"); code != 1 || errb == "" {
		t.Fatalf("root: %d %q", code, errb)
	}
	gatetest.WriteFile(t, p, "version: 1\nmax_tier: operator\nservices:\n  control:\n    units: [\"example-*.service\"]\n    verbs: [restart]\n", 0o644)
	if code, out, errb := run("--policy", p, "--user", "nobody"); code != 1 || out != "" || !strings.Contains(errb, "glob") {
		t.Fatalf("glob unit: %d %q %q", code, out, errb)
	}
	gatetest.WriteFile(t, p, "version: 1\nmax_tier: operator\n", 0o644)
	if code, out, errb := run("--policy", p, "--user", "nobody"); code != 1 || out != "" || !strings.Contains(errb, "services.control") {
		t.Fatalf("no control units: %d %q %q", code, out, errb)
	}
}
