// Package polkit generates the polkit rule for the gate policy's exact
// unit × verb list (docs/POLICY.md §4b).
//
// Verified at the source for systemd 257 (Debian 13) and 259 (Ubuntu 26.04
// LTS): unit start/stop/restart/reload ask polkit for
// org.freedesktop.systemd1.manage-units with the details "unit" (the unit
// id) and "verb" ("start", "stop", "restart", "reload"; "reload-or-…" and
// "try-restart" for other systemctl verbs, which the rule never allows).
// polkit 126 (Debian 13) and 127 (Ubuntu 26.04) run rules with Duktape
// (ECMAScript 5.1); the rule uses nothing newer.
package polkit

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"slices"
	"strings"
)

// Spec is what the rule is generated from.
type Spec struct {
	// User is the service account (subject.user).
	User string
	// Units are exact unit names; Verbs are allowed on every unit.
	Units []string
	Verbs []string
	// PolicySHA256 identifies the policy the rule was generated from.
	PolicySHA256 string
}

// Verbs polkit may be asked to allow (services.control.verbs).
var Verbs = []string{"start", "stop", "restart", "reload"}

var (
	// unitRE is an exact unit name with a type suffix: systemd's unit-name
	// characters, no leading "-", no glob characters.
	unitRE = regexp.MustCompile(`^[A-Za-z0-9:_.\\@][A-Za-z0-9:_.\\@-]{0,254}\.(service|socket|target|timer|mount|automount|path|slice|scope|swap|device)$`)
	userRE = regexp.MustCompile(`^[a-z_][a-z0-9_-]{0,31}$`)
	hexRE  = regexp.MustCompile(`^[0-9a-f]{64}$`)
)

func quote(s string) string {
	b, _ := json.Marshal(s) // a JSON string is an ES5 string literal
	return string(b)
}

// Rule returns the rule text for s. It refuses anything but exact unit
// names, known verbs and a plain user name; there are no wildcards.
func Rule(s *Spec) (string, error) {
	switch {
	case !userRE.MatchString(s.User):
		return "", fmt.Errorf("user %q is not a plain account name", s.User)
	case s.User == "root":
		return "", errors.New("the rule is for the gate's service account, never root")
	case !hexRE.MatchString(s.PolicySHA256):
		return "", errors.New("policy SHA-256 is malformed")
	case len(s.Units) == 0:
		return "", errors.New("services.control.units is empty; no rule is needed")
	case len(s.Verbs) == 0:
		return "", errors.New("services.control.verbs is empty")
	}
	for i, u := range s.Units {
		switch {
		case strings.ContainsAny(u, "*?["):
			return "", fmt.Errorf("unit %q is a glob; polkit rules name exact units only", u)
		case !unitRE.MatchString(u):
			return "", fmt.Errorf("unit %q is not an exact unit name with a type suffix", u)
		case slices.Contains(s.Units[:i], u):
			return "", fmt.Errorf("unit %q is listed twice", u)
		}
	}
	for i, v := range s.Verbs {
		switch {
		case !slices.Contains(Verbs, v):
			return "", fmt.Errorf("verb %q is not start, stop, restart or reload", v)
		case slices.Contains(s.Verbs[:i], v):
			return "", fmt.Errorf("verb %q is listed twice", v)
		}
	}
	verbs := make([]string, len(s.Verbs))
	for i, v := range s.Verbs {
		verbs[i] = quote(v)
	}
	vlist := "[" + strings.Join(verbs, ", ") + "]"
	entries := make([]string, len(s.Units))
	for i, u := range s.Units {
		entries[i] = "    " + quote(u) + ": " + vlist
	}
	var b strings.Builder
	b.WriteString("// Generated by shell-mcp-gate polkit — do not edit by hand.\n")
	b.WriteString("// Policy sha256: " + s.PolicySHA256 + "\n")
	b.WriteString("// Lets " + s.User + " run exactly these systemctl verbs on exactly these units.\n")
	b.WriteString("polkit.addRule(function (action, subject) {\n")
	b.WriteString("  if (action.id !== \"org.freedesktop.systemd1.manage-units\" || subject.user !== " + quote(s.User) + ") {\n")
	b.WriteString("    return polkit.Result.NOT_HANDLED;\n  }\n")
	b.WriteString("  var allowed = {\n" + strings.Join(entries, ",\n") + "\n  };\n")
	b.WriteString("  var unit = action.lookup(\"unit\");\n")
	b.WriteString("  if (typeof unit !== \"string\" || !Object.prototype.hasOwnProperty.call(allowed, unit)) {\n")
	b.WriteString("    return polkit.Result.NOT_HANDLED;\n  }\n")
	b.WriteString("  if (allowed[unit].indexOf(action.lookup(\"verb\")) !== -1) {\n")
	b.WriteString("    return polkit.Result.YES;\n  }\n")
	b.WriteString("  return polkit.Result.NOT_HANDLED;\n});\n")
	return b.String(), nil
}
